#DLP Monitor GUI - passwords are Base64 encoded, not encrypted
#Mon Jul 20 16:24:02 CST 2026
site.1.name=站点B
site.1.username=admin
site.1.host=http\://118.24.71.140\:4200
site.0.name=站点A
format.version=1
site.0.metric.count=0
site.0.username=admin
site.1.metric.count=0
site.1.timeout=20
site.1.enabled=true
site.0.host=http\://118.24.74.26\:3311
site.0.timeout=20
site.0.enabled=true
site.1.password.b64=5L2g55qE5a+G56CB
site.count=2
site.1.verifyTls=false
site.0.password.b64=5L2g55qE5a+G56CB
site.0.verifyTls=false
interval.seconds=300
